#!/bin/sh
#
# Start the devices
#

case "$1" in
  start)
        find /sys/devices/platform/ -name modalias | xargs sort -u | xargs modprobe -abq
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
